### ISSUE TITLE
Problem with jdbc4 driver on Postgres 9.1

### ISSUE THREAD

**Issue by rzeh4n** [NLCR/CZIDLO#108]
After web.web deployment and context configuration this shows up in catalina.out:
Caused by: org.postgresql.util.PSQLException: Method org.postgresql.jdbc4.Jdbc4Connection.isValid(int) is not yet implemented.
	at org.postgresql.Driver.notImplemented(Driver.java:753)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.isValid(AbstractJdbc4Connection.java:102)
	at org.postgresql.jdbc4.Jdbc4Connection.isValid(Jdbc4Connection.java:21)
Looks like old version of jdbc driver.

**Comment by rzeh4n** [comment]
Teda Postgres 9.3

**Comment by rzeh4n** [comment]
Teda Postgres 9.3
