### ISSUE TITLE
OAI Adapter neumí pracovat s deaktivovanými urn:nbn

### ISSUE THREAD

**Issue by rzeh4n** [NLCR/CZIDLO#156]
verze 4.2.2
Pokud je urn:nbn ve stavu DEACTIVATED, OAI Adapter vrátí chybu, resp. záznam má výsledný stav NOT OK.
Napr.:
```
Processing next record - identifier: uuid:d28cb360-7bf0-11e2-b930-005056827e51
- record successfuly transformed to Digital Document Registration data - continuing.
- Digital Document Registration data validation successful - continuing.
- record successfuly transformed to Digital Instance Import data - continuing.
- Digital Instance Import data validation successful - continuing.
- URN:NBN status: UNDEFINED
cz.nkp.urnnbn.oaiadapter.OaiAdapterException: Checking URN:NBN status failed
        at cz.nkp.urnnbn.oaiadapter.OaiAdapter.processSingleDocument(OaiAdapter.java:197)
        at cz.nkp.urnnbn.oaiadapter.OaiAdapter.processRecord(OaiAdapter.java:320)
        at cz.nkp.urnnbn.oaiadapter.OaiAdapter.run(OaiAdapter.java:384)
        at cz.nkp.urnnbn.processmanager.scheduler.jobs.OaiAdapterJob.execute(OaiAdapterJob.java:104)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
STATUS: NOT OK
```

**Comment by rzeh4n** [comment]
Neni jasne, co by se melo dit. Aktualizovat DI u deaktivoavnych DD, nebo ne?

**Comment by rzeh4n** [comment]
Vyřešeno v #105, tedy od verze 4.3
