### ISSUE TITLE
nekonzistenti vystup OAI Adapteru

### ISSUE THREAD

**Issue by rzeh4n** [NLCR/CZIDLO#159]
Vystup oai adapteru (report.txt) v pripade chyby parsovani xml dokumentu, potencialne v jinych situacich, nevyprodukuje konzistentni vystup. Napr:
```
------------------------------------------------------
Processing next record - identifier: uuid:29066d30-0cd2-11e4-a8ab-001018b5eb5c
- record successfuly transformed to Digital Document Registration data - continuing.
cz.nkp.urnnbn.oaiadapter.OaiAdapterException: - Digital Document Registration data invalid - skipping
        at cz.nkp.urnnbn.oaiadapter.OaiAdapter.processRecord(OaiAdapter.java:297)
        at cz.nkp.urnnbn.oaiadapter.OaiAdapter.run(OaiAdapter.java:384)
        at cz.nkp.urnnbn.processmanager.scheduler.jobs.OaiAdapterJob.execute(OaiAdapterJob.java:104)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
Caused by: cz.nkp.urnnbn.oaiadapter.DocumentOperationException: Error: line 2: cvc-minLength-valid: Value '' with length = '0' is not facet-valid with respect to minLength '1' for type 'nonemptyString'.

        at cz.nkp.urnnbn.oaiadapter.utils.XmlTools.validateByXsdAsString(XmlTools.java:141)
        at cz.nkp.urnnbn.oaiadapter.OaiAdapter.processRecord(OaiAdapter.java:293)
        ... 4 more
STATUS: NOT OK
OaiHarvester exception while getting next document: Failed parsing document., url: http://kramerius.mzk.cz/oai/?verb=GetRecord&metadataPrefix=drkramerius4&identifier=uuid:e1bbce70-074f-11e4-a61e-5ef3fc9bb22f
STATUS: NOT OK
------------------------------------------------------
Processing next record - identifier: uuid:1f1ee5c0-fc62-11e3-9789-005056827e52
- record successfuly transformed to Digital Document Registration data - continuing.
cz.nkp.urnnbn.oaiadapter.OaiAdapterException: - Digital Document Registration data invalid - skipping
        at cz.nkp.urnnbn.oaiadapter.OaiAdapter.processRecord(OaiAdapter.java:297)
        at cz.nkp.urnnbn.oaiadapter.OaiAdapter.run(OaiAdapter.java:384)
        at cz.nkp.urnnbn.processmanager.scheduler.jobs.OaiAdapterJob.execute(OaiAdapterJob.java:104)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
Caused by: cz.nkp.urnnbn.oaiadapter.DocumentOperationException: Error: line 2: cvc-minLength-valid: Value '' with length = '0' is not facet-valid with respect to minLength '1' for type 'nonemptyString'.

        at cz.nkp.urnnbn.oaiadapter.utils.XmlTools.validateByXsdAsString(XmlTools.java:141)
        at cz.nkp.urnnbn.oaiadapter.OaiAdapter.processRecord(OaiAdapter.java:293)
        ... 4 more
STATUS: NOT OK
```
Pro uuid:e1bbce70-074f-11e4-a61e-5ef3fc9bb22f chybi oddelovac a hlavicka "Processing next record".

**Comment by rzeh4n** [comment]
Navic se tyhle objekty nezapocitavaji do souhrnu na konci report.txt

**Comment by rzeh4n** [comment]
OAI Adapter i report hodne prekopan, tohle je ted irelevantni.
